### ISSUE TITLE
AttributeError: type object 'BertConfig' has no attribute 'pretrained_config_archive_map'

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/KoBERT-KorQuAD#1]
```
python3 run_squad.py --model_type kobert \
                       --model_name_or_path monologg/kobert \
                       --output_dir models \
                       --data_dir data \
                       --train_file KorQuAD_v1.0_train.json \
                       --predict_file KorQuAD_v1.0_dev.json \
                       --evaluate_during_training \
                       --per_gpu_train_batch_size 8 \
                       --per_gpu_eval_batch_size 8 \
                       --max_seq_length 512 \
                       --logging_steps 4000 \
                       --save_steps 4000 \
                       --do_train
```
```
Traceback (most recent call last):
  File "run_squad.py", line 75, in <module>
    (),
  File "run_squad.py", line 74, in <genexpr>
    (tuple(conf.pretrained_config_archive_map.keys()) for conf in (BertConfig, DistilBertConfig, RobertaConfig, XLNetConfig, XLMConfig)),
AttributeError: type object 'BertConfig' has no attribute 'pretrained_config_archive_map'
```

**Comment by ys7yoo** [comment]
It's a version issue.
https://github.com/huggingface/transformers/issues/5848
https://github.com/huggingface/transformers/issues/6997

**Comment by ys7yoo** [comment]
legacy codes are here
https://github.com/huggingface/transformers/tree/master/examples/legacy/question-answering
